imageType:
  Original: {}

featureClass:
  firstorder: {}
  shape2D: {}      # Только 2D признаки формы для УЗИ
  glcm: {}
  glrlm: {}
  glszm: {}
  gldm: {}
  ngtdm: {}

setting:
  label: 1
  binWidth: 25
  resampledPixelSpacing: null
  interpolator: sitkBSpline
  force2D: true           # КРИТИЧНО для 2D УЗИ
  force2Ddimension: 0
  minimumROIDimensions: 2
  verbose: true
